/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyToggleButton {
        "checked": boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyToggleButtonElement extends Components.MyToggleButton, HTMLStencilElement {
    }
    var HTMLMyToggleButtonElement: {
        prototype: HTMLMyToggleButtonElement;
        new (): HTMLMyToggleButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-toggle-button": HTMLMyToggleButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyToggleButton {
        "checked"?: boolean;
        "onToggleButtonChanged"?: (event: CustomEvent<boolean>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-toggle-button": MyToggleButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-toggle-button": LocalJSX.MyToggleButton & JSXBase.HTMLAttributes<HTMLMyToggleButtonElement>;
        }
    }
}
